// internal/config/cmd/fetchversions/main.go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

type tagResponse struct {
	Results []struct {
		Name string `json:"name"`
	} `json:"results"`
	Next string `json:"next"`
}

// fetchTags fetches up to maxPages of tags for a Docker Hub library image.
func fetchTags(image string, maxPages int) ([]string, error) {
	client := &http.Client{Timeout: 15 * time.Second}
	var tags []string
	url := fmt.Sprintf("https://hub.docker.com/v2/repositories/library/%s/tags?page_size=100", image)

	for page := 0; page < maxPages && url != ""; page++ {
		resp, err := client.Get(url)
		if err != nil {
			return nil, err
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			return nil, fmt.Errorf("Docker Hub returned %d for %s", resp.StatusCode, image)
		}
		var data tagResponse
		if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
			resp.Body.Close()
			return nil, err
		}
		resp.Body.Close()
		for _, r := range data.Results {
			tags = append(tags, r.Name)
		}
		url = data.Next
	}
	return tags, nil
}

// filterPHP extracts major.minor from tags matching "X.Y-fpm" (exact, no suffix).
func filterPHP(tags []string) []string {
	re := regexp.MustCompile(`^(\d+\.\d+)-fpm$`)
	seen := map[string]bool{}
	var versions []string
	for _, t := range tags {
		if m := re.FindStringSubmatch(t); m != nil && !seen[m[1]] {
			seen[m[1]] = true
			versions = append(versions, m[1])
		}
	}
	sortVersionsDesc(versions)
	return versions
}

// filterNode extracts major version from tags matching "X-alpine" (exact).
func filterNode(tags []string) []string {
	re := regexp.MustCompile(`^(\d+)-alpine$`)
	seen := map[string]bool{}
	var versions []string
	for _, t := range tags {
		if m := re.FindStringSubmatch(t); m != nil && !seen[m[1]] {
			seen[m[1]] = true
			versions = append(versions, m[1])
		}
	}
	sortVersionsDesc(versions)
	return versions
}

// filterMajorMinor extracts tags matching bare "X.Y" (digits.digits, no suffix).
func filterMajorMinor(tags []string) []string {
	re := regexp.MustCompile(`^(\d+\.\d+)$`)
	seen := map[string]bool{}
	var versions []string
	for _, t := range tags {
		if m := re.FindStringSubmatch(t); m != nil && !seen[m[1]] {
			seen[m[1]] = true
			versions = append(versions, m[1])
		}
	}
	sortVersionsDesc(versions)
	return versions
}

// filterMajor extracts tags matching bare "X" (single integer, no suffix).
func filterMajor(tags []string) []string {
	re := regexp.MustCompile(`^(\d+)$`)
	seen := map[string]bool{}
	var versions []string
	for _, t := range tags {
		if m := re.FindStringSubmatch(t); m != nil && !seen[m[1]] {
			seen[m[1]] = true
			versions = append(versions, m[1])
		}
	}
	sortVersionsDesc(versions)
	return versions
}

// sortVersionsDesc sorts version strings numerically descending.
// Supports "X" and "X.Y" formats.
func sortVersionsDesc(versions []string) {
	sort.Slice(versions, func(i, j int) bool {
		return compareVersions(versions[i], versions[j]) > 0
	})
}

// compareVersions compares two version strings numerically.
// Returns positive if a > b, negative if a < b, zero if equal.
func compareVersions(a, b string) int {
	aParts := strings.Split(a, ".")
	bParts := strings.Split(b, ".")
	maxLen := len(aParts)
	if len(bParts) > maxLen {
		maxLen = len(bParts)
	}
	for i := 0; i < maxLen; i++ {
		var av, bv int
		if i < len(aParts) {
			av, _ = strconv.Atoi(aParts[i])
		}
		if i < len(bParts) {
			bv, _ = strconv.Atoi(bParts[i])
		}
		if av != bv {
			return av - bv
		}
	}
	return 0
}

type imageSpec struct {
	Name     string
	VarName  string
	Filter   func([]string) []string
	Fallback []string
}

func main() {
	specs := []imageSpec{
		{"php", "PHPVersions", filterPHP, []string{"8.4", "8.3", "8.2", "8.1"}},
		{"node", "NodeVersions", filterNode, []string{"22", "20", "18"}},
		{"mysql", "MySQLVersions", filterMajorMinor, []string{"9.0", "8.4", "8.0"}},
		{"postgres", "PostgresVersions", filterMajor, []string{"17", "16", "15"}},
		{"redis", "RedisVersions", filterMajor, []string{"8", "7"}},
	}

	var b strings.Builder
	b.WriteString("// Code generated by fetchversions; DO NOT EDIT.\n\n")
	b.WriteString("package config\n\n")

	for _, s := range specs {
		tags, err := fetchTags(s.Name, 3)
		versions := s.Fallback
		if err == nil {
			if filtered := s.Filter(tags); len(filtered) > 0 {
				versions = filtered
			}
		}
		fmt.Fprintf(&b, "var %s = []string{", s.VarName)
		for i, v := range versions {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", v)
		}
		b.WriteString("}\n")
	}

	if err := os.WriteFile("versions_generated.go", []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing versions_generated.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("generated versions_generated.go")
}
